from neurapy.robot import Robot
r = Robot()
tool_data = {
    '_controlOA': False,
    '_controlOD': False,
    '_toolOA': False,
    '_toolOD': False,
    'autoM': 0,
    'autoMeasureX': 0,
    'autoMeasureY': 0,
    'autoMeasureZ': 0,
    'closeInput': 0,
    'cmdID': 16,
    'description': 'Tool Description',
    'force': 0,
    'gripper': '',
    'grippertype': 'Standard Gripper',
    'inertiaXX': 0,
    'inertiaXY': 0,
    'inertiaXZ': 0,
    'inertiaYY': 0,
    'inertiaYZ': 0,
    'inertiaZZ': 0,
    'name': 'NoTool',
    'offCOA': [0, 0, 0, 0, 0, 0, 0, 0],
    'offCOD1': 0,
    'offCOD2': 0,
    'offTOA': [0, 0],
    'offTOD': 0,
    'offsetA': 0,
    'offsetB': 0,
    'offsetC': 0,
    'offsetX': 0,
    'offsetY': 0,
    'offsetZ': 0,
    'onCOA': [0, 0, 0, 0, 0, 0, 0, 0],
    'onCOD1': 0,
    'onCOD2': 0,
    'onTOA': [0, 0],
    'onTOD': 0,
    'openInput': 0,
    'portID': '',
    'protocol': 0,
    'robot_type': 'Tool',
    'slaveID': 0,
    'speed': 0
}
tools_data = r.create_tool(tool_data) 